version: '3.8'

services:
  api1:
    image: kennethreitz/httpbin
    restart: always
    ports:
      - 127.0.0.1:8888:80

  api2:
    image: kennethreitz/httpbin
    restart: always

  api3:
    image: kennethreitz/httpbin
    restart: always
